---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: epigos
    service: web
spec:
  type: LoadBalancer
  ports:
    -
      name: http
      port: 80
      targetPort: 5050
    -
      name: https
      port: 443
      targetPort: 443
  selector:
    app: epigos
    service: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: epigos
        service: web
    spec:
      containers:
      - name: web
        image: eu.gcr.io/epigos-ai-dev/newsbot:deploy
        imagePullPolicy: Always
        resources: {}
        command: ["/go/bin/newsbot", "-setup-fb-page=true"]
        envFrom:
        - configMapRef:
            name: env-config
        ports:
          - name: http
            containerPort: 5050
          - name: https
            containerPort: 443

